import os
import resend


class EmailAlertManager:
    def __init__(self):
        api_key = os.getenv("RESEND_API_KEY")

        if not api_key:
            raise ValueError(
                "RESEND_API_KEY environment variable is not set."
            )

        resend.api_key = api_key

        self.sender = os.getenv(
            "ALERT_EMAIL_FROM",
            "onboarding@resend.dev"
        )

        self.recipient = os.getenv("ALERT_EMAIL_TO")

        if not self.recipient:
            raise ValueError(
                "ALERT_EMAIL_TO environment variable is not set."
            )

    def send_alert(self, alert):
        if not alert:
            return False

        level = alert.get("level", "WARNING")
        message = alert.get("message", "Construction site alert detected.")

        subject = f"ConstructAI {level} Alert"

        html = f"""
        <html>
            <body>
                <h2>ConstructAI Safety Alert</h2>

                <p><strong>Alert Level:</strong> {level}</p>

                <p><strong>Message:</strong></p>
                <p>{message}</p>

                <hr>

                <p>
                    This alert was automatically generated by
                    the ConstructAI safety monitoring system.
                </p>
            </body>
        </html>
        """

        try:
            response = resend.Emails.send({
                "from": self.sender,
                "to": [self.recipient],
                "subject": subject,
                "html": html,
            })

            print("Email alert sent:", response)
            return True

        except Exception as e:
            print("Email alert failed:", e)
            return False